-- 코드를 입력하세요
SELECT
    CR.CAR_ID,
    CR.CAR_TYPE,
    ROUND(CR.DAILY_FEE * ((100 - CDP.DISCOUNT_RATE) * 0.01) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRH
ON CR.CAR_ID = CRH.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CDP
ON CR.CAR_TYPE = CDP.CAR_TYPE
WHERE CR.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
    AND CDP.DURATION_TYPE LIKE '30%'
GROUP BY CR.CAR_ID
HAVING CR.CAR_TYPE IN ('세단', 'SUV')
    AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY FEE DESC, CR.CAR_TYPE, CR.CAR_ID DESC