WITH RECURSIVE GenTable AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT o.ID, gt.GENERATION + 1
    FROM ECOLI_DATA o
    JOIN GenTable gt on o.PARENT_ID = gt.ID 
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GenTable gt
WHERE NOT EXISTS (
    SELECT 1 FROM ECOLI_DATA WHERE PARENT_ID = gt.ID
)
GROUP BY GENERATION
ORDER BY GENERATION;
