SELECT
    DISTINCT CRCC.CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR CRCC
JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE
    1 = 1
    AND CRCC.CAR_TYPE = '세단'
    AND CRCRH.START_DATE LIKE '%-10-%'
ORDER BY
    CRCC.CAR_ID DESC
    